[package]
name = "pc_race"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[features]
dynamic_linking = ["bevy/dynamic_linking"]

[dependencies]
bevy = "0.17.3"
sysinfo = "0.37.2"